<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-ISN1DIN" name="com.training.sanity.tests.RETC_039_TEST" tests="8" failures="0" timestamp="21 Mar 2019 05:28:52 GMT" time="67.870" errors="1">
  <testcase name="clkOnPosts" time="3.185" classname="com.training.sanity.tests.RETC_039_TEST"/>
  <testcase name="clkOnCategory" time="5.317" classname="com.training.sanity.tests.RETC_039_TEST"/>
  <testcase name="enterCredential" time="6.833" classname="com.training.sanity.tests.RETC_039_TEST"/>
  <testcase name="clkOnAllPosts" time="1.967" classname="com.training.sanity.tests.RETC_039_TEST"/>
  <testcase name="clkOnAddNewBtn" time="8.279" classname="com.training.sanity.tests.RETC_039_TEST"/>
  <testcase name="actionInAddNewPost" time="31.781" classname="com.training.sanity.tests.RETC_039_TEST"/>
  <testcase name="clkOnChkBox" time="0.159" classname="com.training.sanity.tests.RETC_039_TEST">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.training.pom.RETC_039_POM.clickCatgChkBox(RETC_039_POM.java:218)
at com.training.sanity.tests.RETC_039_TEST.clkOnChkBox(RETC_039_TEST.java:89)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- clkOnChkBox -->
  <testcase name="clkOnPublish" time="10.349" classname="com.training.sanity.tests.RETC_039_TEST"/>
</testsuite> <!-- com.training.sanity.tests.RETC_039_TEST -->
